# Site wide configuration

title: Leap
description: "Pain is inevitable, suffering is optional."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: 
url: http://pengshanyi.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Shanyi Peng
  email: pengshanyi@gmail.com
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
